// -*- tab-width:2 -*-

// Package sim provides a library to specify a distributed system
// discrete event simulation and then run it to generate statistics
package sim

import (
	"math/rand"
)

// Job is work generated by a call to an app instance
// in the app
type Job struct {
	sender       *NodeInterface
	wakeUp       Milliseconds
	startTime    Milliseconds
	TimeoutMs    float64
	pendingCalls map[string]*Node
}
